//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackerControlPanel.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PackerControlPanel.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;{JOB_NAME}&lt;/title&gt;
        ///    &lt;style&gt;
        ///        table {
        ///            font-family: arial, sans-serif;
        ///            border-collapse: collapse;
        ///            width: 100%;
        ///        }
        ///
        ///        td, th {
        ///            border: 1px solid #dddddd;
        ///            text-align: left;
        ///            padding: 8px;
        ///        }
        ///
        ///        tr[name=&quot;Date&quot;] {
        ///            background: #e0e0e0;
        ///        }
        ///
        ///		        tr[n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobDetailedTemplate {
            get {
                return ResourceManager.GetString("JobDetailedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;div style=&quot; border: solid white; border-width: 40px 0px 0px 0px&quot;&gt;&lt;/div&gt;
        ///
        ///	&lt;h1&gt;#{JOB_NAME} Information&lt;/h1&gt;
        ///
        ///	&lt;table&gt;
        ///        &lt;tr&gt;
        ///            &lt;th&gt;Job Name&lt;/th&gt;
        ///            &lt;th&gt;Part Name&lt;/th&gt;
        ///            &lt;th&gt;Total Collected&lt;/th&gt;
        ///            &lt;th&gt;First Seen Date&lt;/th&gt;
        ///            &lt;th&gt;Last Seen Date&lt;/th&gt;
        ///            &lt;th&gt;Status&lt;/th&gt;
        ///        &lt;/tr&gt;
        ///        &lt;tr&gt;
        ///            &lt;td&gt;{JOB_NAME}&lt;/td&gt;
        ///            &lt;td&gt;{PART_NAME}&lt;/td&gt;
        ///            &lt;td&gt;{COLLECTED}&lt;/td&gt;
        ///			&lt;td&gt;{FIRST_SEEN}&lt;/td&gt;
        ///			&lt;td&gt;{LA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobEntryTemplate {
            get {
                return ResourceManager.GetString("JobEntryTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;{RECEIVER_NAME}&lt;/title&gt;
        ///    &lt;style&gt;
        ///        table {
        ///            font-family: arial, sans-serif;
        ///            border-collapse: collapse;
        ///            width: 100%;
        ///        }
        ///
        ///        td, th {
        ///            border: 1px solid #dddddd;
        ///            text-align: left;
        ///            padding: 8px;
        ///        }
        ///
        ///        tr[name=&quot;Date&quot;] {
        ///            background: #e0e0e0;
        ///        }
        ///
        ///        t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReceiverDetailedTemplate {
            get {
                return ResourceManager.GetString("ReceiverDetailedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;{RECEIVER_NAME}&lt;/title&gt;
        ///    &lt;style&gt;
        ///        table {
        ///            font-family: arial, sans-serif;
        ///            border-collapse: collapse;
        ///            width: 100%;
        ///        }
        ///
        ///        td, th {
        ///            border: 1px solid #dddddd;
        ///            text-align: left;
        ///            padding: 8px;
        ///            padding-top: 30px;
        ///            padding-bottom: 30px;
        ///        }
        ///
        ///        tr[name= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReceiverDetailedTemplate1 {
            get {
                return ResourceManager.GetString("ReceiverDetailedTemplate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style&gt;
        ///        @page {
        ///            size: auto; /* auto is the current printer page size */
        ///            margin: 0mm; /* this affects the margin in the printer settings */
        ///        }
        ///
        ///        body {
        ///            font-family: Calibri;
        ///            font-weight: bold;
        ///            text-align: center;
        ///        }
        ///
        ///        #footer {
        ///            position: fixed;
        ///            left: 0;
        ///            bottom: 0;
        ///            width: 100%;
        ///            margin-left: auto;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SkidTemplate {
            get {
                return ResourceManager.GetString("SkidTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;{TRANSFER_NAME}&lt;/title&gt;
        ///    &lt;style&gt;
        ///        table {
        ///            font-family: arial, sans-serif;
        ///            border-collapse: collapse;
        ///            width: 100%;
        ///			break-inside: avoid;
        ///        }
        ///
        ///		tr    { page-break-inside:avoid; page-break-after:auto }
        ///		thead { display:table-header-group; }
        ///		tfoot { display:table-footer-group; }
        ///
        ///        td, th {
        ///            border: 1px s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransferDetailedTemplate {
            get {
                return ResourceManager.GetString("TransferDetailedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;div style=&quot; border: solid white; border-width: 40px 0px 0px 0px&quot;&gt;&lt;/div&gt;
        ///	&lt;table&gt;
        ///        &lt;tr&gt;
        ///            &lt;th&gt;Part Name&lt;/th&gt;
        ///            &lt;th&gt;Work Order&lt;/th&gt;
        ///            &lt;th&gt;Received Location&lt;/th&gt;
        ///        &lt;/tr&gt;
        ///        &lt;tr&gt;
        ///            &lt;td&gt;{PART_NAME} &lt;br /&gt;&lt;t name=&quot;element_barcode&quot;&gt;*{PART_NAME}*&lt;/t&gt;&lt;/td&gt;
        ///            &lt;td&gt;{JOB_NAME}&lt;/td&gt;
        ///            &lt;td&gt;{RECEIVED_LOCATION} &lt;br /&gt;&lt;t name=&quot;element_barcode&quot;&gt;*{RECEIVED_LOCATION}*&lt;/t&gt;&lt;/td&gt;
        ///        &lt;/tr&gt;
        ///        &lt;tr&gt;
        ///            &lt;td&gt;
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransferEntryTemplate {
            get {
                return ResourceManager.GetString("TransferEntryTemplate", resourceCulture);
            }
        }
    }
}
